"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express = require('express');
const router = express.Router();
const handleErrorAsync_1 = __importDefault(require("../utils/handleErrorAsync"));
const PostController_1 = __importDefault(require("../controllers/PostController"));
const isAuth_1 = __importDefault(require("../middlewares/isAuth"));
router.get('/', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.getPosts));
router.post('/', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.insertPost));
router.delete('/', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.delAllPosts));
router.delete('/:postID', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.delSinglePost));
router.patch('/:postID', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.updatePostContent));
router.get('/:postID', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.getSinglePost));
router.get('/user/:userID', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.getUserPosts));
router.post('/:postID/like', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.clickPostLike));
router.delete('/:postID/unlike', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.cancelPostLike));
router.post('/:postID/comment', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.insertComment));
router.get('/:postID/comments', isAuth_1.default, (0, handleErrorAsync_1.default)(PostController_1.default.getAllComments));
exports.default = router;
