"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
const handleErrorAsync_1 = __importDefault(require("../utils/handleErrorAsync"));
const UserController_1 = __importDefault(require("../controllers/UserController"));
const isAuth_1 = __importDefault(require("../middlewares/isAuth"));
router.post('/sign_up', (0, handleErrorAsync_1.default)(UserController_1.default.insertUser));
router.post('/sign_in', (0, handleErrorAsync_1.default)(UserController_1.default.searchUserLogin));
router.patch('/updatePassword', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.updateUserPassword));
router.get('/profile', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.getUser));
router.patch('/profile', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.updateUserInfo));
router.get('/getLikeList', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.getUserLikePostList));
router.post('/:userID/follow', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.followUser));
router.delete('/:userID/unfollow', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.cancelFollowUser));
router.get('/following', isAuth_1.default, (0, handleErrorAsync_1.default)(UserController_1.default.getUserFollowing));
exports.default = router;
